---
title: "myTimeSteppingExampleR"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r timestep, echo=FALSE}
#### Initial State - starting position, heading angle, time step
TimeStep <- function(heading_angle, samples, timestep, speed, SimulationTime){ # now timestep is a function, user can input any parameters and plot the results.

startpos_x <- 0
startpos_y <- 0
heading_angle <- heading_angle # 5 # degrees of the heading offset
heading_angle <- heading_angle * pi /180 # converting to degrees
samples <- samples # 5 # per second 
timestep <- timestep / samples # 1 / samples
speed <- speed # 10 # in metres per second

SimulationTime <- SimulationTime # in seconds
TotalSamples <- SimulationTime * samples # number of samples allowed within the simulation time 


X <- numeric(TotalSamples) # x the rows length of number of samples
Y <- numeric(TotalSamples) # y the rows length of number of samples

#### Update loop

for (i in 1:TotalSamples) { # for index in length of total samples
    if (i > 1) { # if the index is more than 1
        X[i] = X[i-1] + # the index of the x vector of zeros is equal to the index minus 1 plus
        cos(heading_angle) * speed * timestep # the cosine of the heading angle mulitpled by speed multiplied by the timestep
        Y[i] = Y[i-1] + # the index of the y vector of zeros is equal to the index minus 1 plus
        sin(heading_angle) * speed * timestep # the sine of the heading angle mulitpled by speed multiplied by the timestep
    }
}

#### plotting 

 plot(X, Y)

 ### Dataframe and saving

x_y_coordinates <- data.frame(X, Y) # saving x and y coords in dataframe

View(x_y_coordinates) # view the new dataframe

write.csv(x_y_coordinates, file = "myTimeSteppingExampleDataR.csv") # writes dataframe to .csv file
return(x_y_coordinates)
}

```

